version: '2.4'
services:
  iris:
    build: .
    restart: always
    volumes:
      # - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/iris/app
    networks: 
      default:
        ipv4_address: 192.169.250.2
networks:
  default:
   ipam:
      driver: default
      config:
        - subnet: 192.169.250.0/16
          gateway: 192.169.250.1