/// 
Class BestOffer.Rule.DiscountRule Extends Ens.Rule.Definition
{

Parameter RuleAssistClass = "Ens.Rule.GeneralBusinessRuleAssist";

XData RuleDefinition [ XMLNamespace = "http://www.intersystems.com/rule" ]
{
<ruleDefinition alias="" context="BestOffer.BP.FindMatchingBuyersBpl.Context" production="">
<ruleSet name="" effectiveBegin="" effectiveEnd="">
<return>10</return>
</ruleSet>
</ruleDefinition>
}

}
